---

- name: 'Install uwsgi packages'
  become: True
  apt:
    name: "{{ item }}"
    state: "{{ uwsgi_package_state }}"
    update_cache: True
    cache_valid_time: 3600
  with_items: "{{ uwsgi_packages }}"
  notify:
    - 'Restart uwsgi'
