---

# Handlers main file for uwsgi role

- name: 'HANDLER | Restart uwsgi'
  become: True
  service:
    name: "{{ uwsgi_service_name }}"
    state: 'restarted'
  tags:
    - 'role::uwsgi'
    - 'role::uwsgi::config'
    - 'role::uwsgi::install'
