---

# Handlers main file for uwsgi role

- name: 'HANDLER | Restart uwsgi'
  become: True
  service:
    name: "{{ uwsgi_service_name }}"
    state: 'restarted'
  when:
    - 'uwsgi_restart_handler_enabled'
    - 'not uwsgi_install_emperor'
  tags:
    - 'role::uwsgi'
    - 'role::uwsgi::config'
    - 'role::uwsgi::install'

- name: 'HANDLER | Start uwsgi emperor'
  become: True
  service:
    name: "{{ item.service_name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ uwsgi_emperor }}"
  when:
    - 'uwsgi_restart_handler_enabled'
    - 'uwsgi_install_emperor'
  tags:
    - 'role::uwsgi'
    - 'role::uwsgi::config'
    - 'role::uwsgi::install'
