---

# Role tests

- name: 'Converge | Prerequisites tasks'
  hosts: 'all'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7'
      become: True
      raw: 'apt-get install -qq python2.7'
      changed_when: False


- name: 'Converge | Main tasks'
  hosts: 'all'
  pre_tasks:
    - block:
        - name: 'Install test system dependencies'
          apt:
            name: "{{ item }}"
            state: 'present'
          with_items:
            - 'net-tools'
            - 'python-dev'
            - 'python-pip'
            - 'sudo'
          changed_when: False
  roles:
    - role: "ansible-role-uwsgi"
